README.md, package.json
@lpatiny @targos @stropitek what do you think?
=> Api proposal

README.md, package.json, src/Plot.tsx, src/components/LineSeries.tsx, src/hooks.ts, src/index.ts, src/types.ts, src/utils.ts, stories/plot.stories.tsx
Not a big fan of long PR, so the idea is just to display the line series
https://deploy-preview-2--amazing-kilby-d9c1d7.netlify.app/?path=/story/example-plot--control
=> Base implementation

src/components/XAxis.tsx, src/components/YAxis.tsx, src/types.ts, stories/plot.stories.tsx
Compatible with [d3-format](https://github.com/d3/d3-format)
=> feat: add label format

src/Plot.tsx
=> chore: default state numbers are 0

.storybook/main.js, package.json, src/Plot.tsx, src/components/LineSeries.tsx, src/components/XAxis.tsx, src/components/YAxis.tsx, src/types.ts, src/utils.ts, stories/plot.stories.tsx
- add tickStyle to the axis, allowing to add styles (uses kebab-case)
- add the source to the stories
- fix the default color palette error
=> Tick style

src/Plot.tsx, src/components/Legend.tsx, src/components/LineSeries.tsx, src/types.ts, stories/axis-boundaries.stories.tsx, stories/examples/iris-dataset.stories.tsx, stories/plot.stories.tsx
=> changing API from{x:[],y:[]} to [{x,y}]

src/PlotObject.tsx, src/index.ts, src/types.ts, stories/plot-object.stories.tsx
=> feat: adds a single prop component to render plot

package.json, src/Plot.tsx, src/PlotObject.tsx, src/components/Axis.tsx, src/components/XAxis.tsx, src/components/YAxis.tsx, src/index.ts, src/types.ts, src/utils.ts, stories/axis-boundaries.stories.tsx, stories/examples/iris-dataset.stories.tsx, stories/plot-object.stories.tsx, stories/plot.stories.tsx
- Migrates implementation on Axis using react to modify the DOM
- Merge both Axis and display depending on the position (currently only accepts 'vertical' and 'horizontal')
- Simplify reducers with immerjs
This preparates the work for #54, #59, and #60
=> Axis react

.eslintrc.yml, src/Plot.tsx, src/PlotObject.tsx, src/components/Axis/BottomAxis.tsx, src/components/Axis/LeftAxis.tsx, src/components/Axis/RightAxis.tsx, src/components/Axis/TopAxis.tsx, src/components/Axis/index.tsx, src/components/LineSeries.tsx, src/components/ScatterSeries.tsx, src/hooks.ts, src/types.ts, src/utils.ts, stories/axis-boundaries.stories.tsx, stories/examples/iris-dataset.stories.tsx, stories/plot-object.stories.tsx, stories/plot.stories.tsx
=> Multiple axis

src/Plot.tsx, src/PlotObject.tsx, src/types.ts, stories/plot-object.stories.tsx
=> Viewport style

src/components/LineSeries.tsx, src/components/ScatterSeries.tsx, src/types.ts, stories/examples/iris-dataset.stories.tsx
- hide scatter or line series
- optional id (adds the same color to line and scatter series)
- line series extends scatter series
closes #49
=> feat: allows to hide series and specify serie id

src/components/Markers.tsx, src/components/ScatterSeries.tsx, src/types.ts, src/utils.ts, stories/plot-object.stories.tsx
=> feat: marker style allows to a property to be a function

src/components/Axis/BottomAxis.tsx, src/components/Axis/LeftAxis.tsx, src/components/Axis/RightAxis.tsx, src/components/Axis/TopAxis.tsx, src/components/Axis/index.tsx, src/types.ts, stories/plot.stories.tsx
=> feat: add showTicks props on Axis

src/components/Axis/BottomAxis.tsx, src/components/Axis/LeftAxis.tsx, src/components/Axis/RightAxis.tsx, src/components/Axis/TopAxis.tsx, src/components/Axis/index.tsx, src/types.ts, stories/axis-boundaries.stories.tsx
=> feat: add option for getting ticks inside the axis

src/components/LineSeries.tsx
=> fix: set the marker to be in front of line

src/components/Axis/BottomAxis.tsx, src/components/Axis/LeftAxis.tsx, src/components/Axis/RightAxis.tsx, src/components/Axis/Ticks.tsx, src/components/Axis/TopAxis.tsx
=> refactor: rename show in Ticks props

src/components/VerticalText.tsx, src/utils.ts, stories/control/axis.stories.tsx, stories/control/heading.stories.tsx, stories/control/legend.stories.tsx, stories/control/line.stories.tsx, stories/control/plot.stories.tsx, stories/control/scatter.stories.tsx
=> docs: add some example & control in storybook

src/components/Axis/index.tsx, src/hooks.ts, src/plotReducer.ts, src/types.ts, stories/axis-boundaries.stories.tsx, stories/control/axis.stories.tsx, stories/control/line.stories.tsx, stories/control/plot.stories.tsx, stories/examples/iris-dataset.stories.tsx, stories/examples/nasdaq.stories.tsx, stories/spectra/infrared.stories.tsx, stories/spectra/nmr.stories.tsx, stories/spectra/raman.stories.tsx, stories/spectra/tga.stories.tsx
=> Sebastien ahkrin/issue/104

src/Plot.tsx, src/components/Legend.tsx, src/components/LineSeries.tsx, src/components/legendsContext.tsx, stories/control/legend.stories.tsx
Fixes #108
Fixes #109
Fixes #110
=> fix: change the Legend to use the marker

stories/examples/covid-cases.stories.tsx, stories/examples/nasdaq.stories.tsx, stories/spectra/infrared.stories.tsx, stories/spectra/nmr.stories.tsx, stories/spectra/raman.stories.tsx, stories/spectra/tga.stories.tsx, stories/utils.ts
=> docs: add DEFAULT_VALUES keys to a utils file

stories/control/axis.stories.tsx
=> docs: remove unused controls

src/components/Axis/BottomAxis.tsx, src/components/Axis/TopAxis.tsx, src/utils.ts
=> fix: Ticks overlap 

src/components/Legend.tsx, src/components/Markers.tsx, src/components/ScatterSeries.tsx, src/components/legendsContext.tsx, src/types.ts, stories/control/line.stories.tsx, stories/examples/iris-dataset.stories.tsx, stories/examples/shapes.stories.tsx
=> feat: add more shapes

src/components/Axis/BottomAxis.tsx, src/components/Axis/LeftAxis.tsx, src/components/Axis/RightAxis.tsx, src/components/Axis/Ticks.tsx, src/components/Axis/TopAxis.tsx, src/components/Axis/index.tsx, src/types.ts, src/utils.ts
=> feat: add secondary ticks 

src/components/BarSeries.tsx, src/index.ts, src/utils.ts, stories/control/bar.stories.tsx, stories/control/line.stories.tsx
=> feat: add bar series component

.storybook/preview.js, README.md, package.json, src/Plot.tsx, src/PlotObject.tsx, src/index.ts, src/types.ts, stories/control/axis.stories.tsx, stories/control/bar.stories.tsx, stories/control/heading.stories.tsx, stories/control/legend.stories.tsx, stories/control/line.stories.tsx, stories/control/plot.stories.tsx, stories/control/scatter.stories.tsx, stories/examples/covid-cases.stories.tsx, stories/examples/nasdaq.stories.tsx, stories/plot-object.stories.tsx, stories/spectra/infrared.stories.tsx, stories/spectra/nmr.stories.tsx, stories/spectra/raman.stories.tsx, stories/spectra/tga.stories.tsx
https://deploy-preview-140--amazing-kilby-d9c1d7.netlify.app/?path=/story/api-plot--plot-control
=> Improve docs and add svgStyle prop

src/components/Axis/BottomAxis.tsx, src/components/Axis/LeftAxis.tsx, src/components/Axis/RightAxis.tsx, src/components/Axis/TopAxis.tsx
=> fix: Tick text aligned according to ticks length

src/components/ScatterSeries.tsx
=> fix: remove the stroke color from a Marker

package.json, src/components/Legend.tsx, stories/axis-boundaries.stories.tsx, stories/control/legend.stories.tsx
Depends on https://github.com/zakodium/react-d3-utils/pull/10
=> fix: use align group to align embedded legend

README.md, package.json, src/components/BarSeries.tsx, src/components/LineSeries.tsx, src/components/legendsContext.tsx, stories/plot.stories.tsx
=> fix: remove legend on unmount

src/components/Annotations/Annotation.tsx, src/components/Annotations/Arrow.tsx, src/components/Annotations/Circle.tsx, src/components/Annotations/Ellipse.tsx, src/components/Annotations/Group.tsx, src/components/Annotations/Line.tsx, src/components/Annotations/MarkerDefs.tsx, src/components/Annotations/Rectangle.tsx, src/components/Annotations/Shape.tsx, src/components/Annotations/Text.tsx, src/hooks.ts, src/index.ts, stories/annotations/annotation.data.tsx, stories/annotations/annotations.stories.tsx, stories/annotations/arrow.stories.tsx, stories/annotations/circle.stories.tsx, stories/annotations/ellipse.stories.tsx, stories/annotations/group.stories.tsx, stories/annotations/rectangle.stories.tsx
fixes: #152
fixes: #153
fixes: #154
fixes: #155
fixes: #156
fixes: #157
=> docs: add control stories

package.json, src/components/Axis/BottomLogAxis.tsx, src/components/Axis/LeftLogAxis.tsx, src/components/Axis/RightLogAxis.tsx, src/components/Axis/TicksLog.tsx, src/components/Axis/TopLogAxis.tsx, src/components/Axis/index.tsx, src/hooks.ts, src/types.ts, stories/control/logaxis.stories.tsx, stories/plot-object.stories.tsx
It needs to be migrated the linear scale to `react-d3-utils` and added the secondary ticks to that library.
=> feat: add logScale

package.json
=> docs: add contributors

src/components/LineSeries.tsx, stories/control/legend.stories.tsx
=> fix: doesn't show legend if series is hidden

src/PlotObject.tsx, src/components/Annotations/Line.tsx, src/components/Annotations/Shape.tsx, src/components/Annotations/Text.tsx, src/types.ts, stories/annotations/annotations.stories.tsx, stories/plot-object.stories.tsx
- add an annotation to the single prop of `PlotObject`
- add annotations as children of `PlotObject`
closes #181
=> Annotations PlotObject

package.json, src/components/Annotations/Group.tsx, src/components/Annotations/Line.tsx, stories/plot-object.stories.tsx
https://deploy-preview-195--react-plot.netlify.app/?path=/story/plot-plot-object--control
=> feat: add relative position to line annotation

src/components/Annotations/Group.tsx, src/hooks.ts, src/index.ts, stories/annotations/group.stories.tsx
Closes: https://github.com/zakodium/react-plot/issues/219
=> feat: support alignment of annotation groups

stories/examples/pca.stories.tsx
creating pca example using ScatterSeries and ellipse annotation
=> docs : Pca example

src/components/Plot.tsx, src/components/Tracking.tsx, stories/control/zoom.stories.tsx
close https://github.com/zakodium/react-plot/issues/199
=> Docs : Add example with zoom principle 

stories/spectra/mass.stories.tsx
close https://github.com/zakodium/react-plot/issues/240
=> feat: add advanced zoom example story

src/components/Annotations/Arrow.tsx, src/components/Annotations/MarkerDefs.tsx, stories/annotations/arrow.stories.tsx
closes : https://github.com/zakodium/react-plot/issues/243
=> Feat : add strokeWidth & markerWidth props to arrow annotation

src/components/Legend.tsx, src/components/Plot.tsx, src/contexts/legendOffsetContext.ts, src/plotContext.ts, src/utils/splitChildren.tsx, src/utils/usePlotSizes.ts, stories/control/legend.stories.tsx
Closes: https://github.com/zakodium/react-plot/issues/212
=> fix: resize plot for and place legend correctly

stories/axis-boundaries.stories.tsx, stories/control/bar.stories.tsx, stories/control/line.stories.tsx, stories/control/parallelaxis.stories.tsx, stories/control/range.stories.tsx, stories/control/scatter.stories.tsx, stories/examples/nasdaq.stories.tsx, stories/plot.stories.tsx
closes : https://github.com/zakodium/react-plot/issues/210
=> docs : Replace argTypes with defaultValue with args

src/components/Annotations/Polyline.tsx, src/components/Annotations/Shape.tsx, stories/annotations/callback.stories.tsx, stories/examples/callback.stories.tsx
closes : https://github.com/zakodium/react-plot/issues/236
=> docs : Example with annotation callback

src/components/Axis/Axis.tsx, src/components/Axis/HorizontalAxis.tsx, src/components/Axis/HorizontalAxisGridLines.tsx, src/components/Axis/HorizontalAxisLine.tsx, src/components/Axis/ParallelAxis.tsx, src/components/Axis/Ticks.tsx, src/components/Axis/VerticalAxis.tsx, src/components/Axis/VerticalAxisGridLines.tsx, src/components/Axis/VerticalAxisLine.tsx, src/components/Axis/types.ts, stories/control/axis.stories.tsx
closes : https://github.com/zakodium/react-plot/issues/214
closes : https://github.com/zakodium/react-plot/issues/239
=> implement all missing axis props & fix Position of tick labels

src/hooks.ts, stories/annotations/mixed.stories.tsx, stories/examples/mixed.stories.tsx
closes : https://github.com/zakodium/react-plot/issues/237
=> feat :  x / y coordinates as "%"

stories/spectra/infrared.stories.tsx
closes : https://github.com/zakodium/react-plot/issues/263
=> feat: Cross hair

src/components/Axis/Axis.tsx, src/components/Axis/HorizontalAxis.tsx, src/components/Axis/LinearAxis.tsx, src/components/Axis/LogAxis.tsx, src/components/Axis/ParallelAxis.tsx, src/components/Axis/Ticks.tsx, src/components/Axis/VerticalAxis.tsx, src/components/Axis/types.ts, stories/control/axis.stories.tsx
closes : https://github.com/zakodium/react-plot/issues/264
=> feat: Axis secondaryTick

src/components/Plot.tsx, src/components/Tracking.tsx, stories/spectra/mass.stories.tsx
closes : https://github.com/zakodium/react-plot/issues/251
=> Feat : add pan and vertical scale

src/components/Axis/Ticks.tsx, src/components/Plot.tsx, src/components/VerticalText.tsx
Closes: https://github.com/zakodium/react-plot/issues/273
=> fix: disable text selection on all plot elements by default

stories/spectra/nmr.stories.tsx
closes : https://github.com/zakodium/react-plot/issues/282
=> docs: stacked spectra 

src/hooks/index.ts, src/hooks/useCrossHair.tsx, stories/spectra/infrared.stories.tsx
closes : https://github.com/zakodium/react-plot/issues/303
=> Feat: useCrossHair Hook 

src/components/Plot.tsx, src/contexts/plotController/nestableContext.tsx, src/contexts/plotController/plotControllerContext.tsx, src/hooks/types.ts, src/hooks/useAxisZoom.tsx, src/hooks/useCrossHair.tsx, src/hooks/useDrawRectangle.tsx, src/hooks/useRectangularZoom.tsx, src/hooks/useStartMoveEnd.ts, stories/examples/nested-zoom.stories.tsx
Closes: https://github.com/zakodium/react-plot/issues/298
=> feat: add support for nested PlotController contexts

stories/examples/spectrum2d.stories.tsx
closes : https://github.com/zakodium/react-plot/issues/315
=> docs: add zoom to 2d spectrum

src/contexts/plotContext.ts, stories/examples/weatherchart.stories.tsx
closes : https://github.com/zakodium/react-plot/issues/348
=> fix: axes domain

src/components/Series/BarSeries.tsx, src/components/Series/LineSeries.tsx, src/components/Series/ScatterSeries.tsx, stories/axis-boundaries.stories.tsx, stories/control/bar.stories.tsx, stories/control/legend.stories.tsx, stories/control/line.stories.tsx, stories/control/parallelaxis.stories.tsx, stories/examples/bitcoin.stories.tsx, stories/examples/color-serie.stories.tsx, stories/examples/draw.stories.tsx, stories/examples/zoom.stories.tsx, stories/plot.stories.tsx
closes : https://github.com/zakodium/react-plot/issues/355
=> chore!: displayMarker to displayMarkers

src/components/Plot.tsx, src/utils/splitChildren.tsx, stories/examples/zoom.stories.tsx
closes : https://github.com/zakodium/react-plot/issues/353
=> feat!: plot svg layers

src/components/Legend.tsx, src/components/Plot.tsx, stories/control/legend.stories.tsx
closes : https://github.com/zakodium/react-plot/issues/367
=> Fix: legend

src/components/Series/RangeSeries.tsx
closes : https://github.com/zakodium-oss/react-plot/issues/372
=> Default lineStyle value in RangeSeries

src/components/Annotations/Arrow.tsx, src/components/Annotations/Circle.tsx, src/components/Annotations/DirectedEllipse.tsx, src/components/Annotations/Ellipse.tsx, src/components/Annotations/Group.tsx, src/components/Annotations/Line.tsx, src/components/Annotations/MarkerDefs.tsx, src/components/Annotations/Polygon.tsx, src/components/Annotations/Polyline.tsx, src/components/Annotations/Rectangle.tsx, src/components/Annotations/Shape.tsx, src/components/Annotations/Text.tsx, src/components/Axis/Axis.tsx, src/contexts/plotContext.ts, src/hooks.ts, src/index.ts, src/types.ts, stories/examples/shift.stories.tsx
closes : https://github.com/zakodium-oss/react-plot/issues/370
=> feat: add ScalarValue type

src/components/Series/BarSeries.tsx, src/components/Series/LineSeries.tsx
closes : https://github.com/zakodium-oss/react-plot/issues/376
closes : https://github.com/zakodium-oss/react-plot/issues/374
=> fix: ErrorBar & PointLabel

src/components/Series/ScatterSeries.tsx
closes : https://github.com/zakodium-oss/react-plot/issues/371
=> Fix ScatterSeries Simple markersShape in Legend

src/components/Axis/Axis.tsx, src/contexts/plotContext.ts, stories/spectra/nmr.stories.tsx
closes : https://github.com/zakodium-oss/react-plot/issues/387
=> Optimisation

stories/examples/iris-dataset.stories.tsx
fix duplcated id , Infinite rendring
=> docs: fix iris PCA story

src/components/Series/BarSeries.tsx, src/components/Series/LineSeries.tsx
closes : https://github.com/zakodium-oss/react-plot/issues/400
=> fix: Performance issue with LineSeries & BarSeries

src/components/Axis/HorizontalAxis.tsx, src/components/Axis/HorizontalAxisGridLines.tsx, src/components/Axis/VerticalAxis.tsx, src/components/Axis/VerticalAxisGridLines.tsx
closes : https://github.com/zakodium-oss/react-plot/issues/401
=> feat: make primary & secondary grids independent

src/components/Annotations/Arrow.tsx, src/components/Annotations/BoxPlot.tsx, src/components/Annotations/Circle.tsx, src/components/Annotations/DirectedEllipse.tsx, src/components/Annotations/Ellipse.tsx, src/components/Annotations/Group.tsx, src/components/Annotations/Line.tsx, src/components/Annotations/Polygon.tsx, src/components/Annotations/Polyline.tsx, src/components/Annotations/Rectangle.tsx, src/components/Annotations/Shape.tsx, src/components/Annotations/Text.tsx, src/hooks.ts, stories/examples/callback.stories.tsx
closes : https://github.com/zakodium-oss/react-plot/issues/407
=> feat: add xAxis & yAxis to annotations

src/hooks/types.ts, src/hooks/useAxisWheelZoom.tsx, src/hooks/useAxisZoom.tsx, src/hooks/useCrossHair.tsx, src/hooks/useDrawPath.tsx, src/hooks/useDrawRectangle.tsx
closes : https://github.com/zakodium-oss/react-plot/issues/415
=> docs: document hook properties

src/contexts/plotController/plotControllerContext.tsx, src/hooks/types.ts, src/hooks/useAxisZoom.tsx, src/hooks/useDrawPath.tsx, src/hooks/useDrawRectangle.tsx, stories/examples/draw.stories.tsx, stories/examples/lassoselection.stories.tsx, stories/examples/spectrum2d.stories.tsx, stories/examples/zoom.stories.tsx, stories/spectra/infrared.stories.tsx, stories/spectra/mass.stories.tsx
closes : https://github.com/zakodium-oss/react-plot/issues/417
=> Disabled hooks

package.json, src/components/Series/Series.tsx, src/index.ts, src/utils/splitChildren.tsx, stories/examples/iris-dataset.stories.tsx
- chore: update dependencies
- feat: add `Series` wrapper component
=> Add Series wrapper component

package.json
Closes: https://github.com/zakodium-oss/react-plot/issues/445
=> chore: remove npm overrides

package.json, src/components/Series/ScatterSeries.tsx, tsconfig.esm.json, tsconfig.json
- fix: add missing key to scatter lines
- fix: include src folder in build
- chore: update tsconfig
=> Small ScatterSeries improvements

package.json, tests/serverside.test.tsx, tests/utils.tsx
closes https://github.com/zakodium-oss/react-plot/issues/457
=> test: react-plot on server side

tsconfig.json
- Check file name casing in imports
- Explicitly disallow JS
=> chore: add two fields to tsconfig
